tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-container": "#cea700",
                "on-primary-container": "#fefcff",
                "on-primary-fixed": "#001a42",
                "surface": "#f9f9f9",
                "surface-bright": "#f9f9f9",
                "on-tertiary-fixed": "#231b00",
                "secondary-container": "#6bff8f",
                "surface-container-high": "#e8e8e8",
                "inverse-surface": "#303030",
                "surface-container-low": "#f3f3f3",
                "surface-container": "#eeeeee",
                "secondary-fixed": "#6bff8f",
                "on-tertiary-fixed-variant": "#574500",
                "tertiary-fixed-dim": "#eec200",
                "secondary-fixed-dim": "#4ae176",
                "on-background": "#1b1b1b",
                "outline-variant": "#c2c6d6",
                "primary": "#0058be",
                "surface-variant": "#e2e2e2",
                "error-container": "#ffdad6",
                "on-tertiary-container": "#4e3e00",
                "primary-fixed-dim": "#adc6ff",
                "surface-container-lowest": "#ffffff",
                "secondary": "#006e2f",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed": "#002109",
                "inverse-on-surface": "#f1f1f1",
                "outline": "#727785",
                "tertiary-fixed": "#ffe083",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "primary-fixed": "#d8e2ff",
                "on-surface": "#1b1b1b",
                "tertiary": "#735c00",
                "background": "#f9f9f9",
                "surface-container-highest": "#e2e2e2",
                "on-secondary-container": "#007432",
                "error": "#ba1a1a",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#004395",
                "on-secondary-fixed-variant": "#005321",
                "surface-tint": "#005ac2",
                "surface-dim": "#dadada",
                "on-surface-variant": "#424754",
                "inverse-primary": "#adc6ff",
                "primary-container": "#2170e4",
                "on-error": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "container-max": "1280px",
                "gutter": "24px",
                "base": "8px",
                "margin-mobile": "16px",
                "margin-desktop": "64px"
            },
            "fontFamily": {
                "display": ["Space Grotesk"],
                "body": ["Bricolage Grotesque"],
                "headline-lg-mobile": ["Space Grotesk"],
                "body-md": ["Bricolage Grotesque"],
                "label-bold": ["Space Grotesk"],
                "display-xl": ["Space Grotesk"],
                "body-lg": ["Bricolage Grotesque"],
                "headline-md": ["Space Grotesk"],
                "headline-lg": ["Space Grotesk"]
            },
            "fontSize": {
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "label-bold": ["14px", {"lineHeight": "20px", "fontWeight": "700"}],
                "display-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
            }
        },
    },
}